import { createHash, randomBytes, randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { ContentCipher } from "./crypto.js";
import { assertAuthorized, createAdminPasswordHash, KnowledgeOpsAuthorizer, StaticTokenAuthorizer } from "./rbac.js";

describe("knowledge ops security",()=>{
  it("encrypts content with authenticated encryption and rejects tampering",()=>{const cipher=new ContentCipher(randomBytes(32));const payload=cipher.encrypt({question:"机密问题",answer:"机密答案"});expect(JSON.stringify(payload)).not.toContain("机密");expect(cipher.decrypt(payload)).toEqual({question:"机密问题",answer:"机密答案"});const replacement=payload.data.startsWith("A")?"B":"A";expect(()=>cipher.decrypt({...payload,data:`${replacement}${payload.data.slice(1)}`})).toThrow("content_cipher_decryption_failed");});
  it("decrypts historical payloads after rotating the current encryption key",()=>{const first=randomBytes(32),second=randomBytes(32);const old=new ContentCipher(first,1);const payload=old.encrypt({question:"旧问题"});const rotated=new ContentCipher(second,2,new Map([[1,first],[2,second]]));expect(rotated.decrypt(payload)).toEqual({question:"旧问题"});expect(rotated.encrypt({question:"新问题"}).keyVersion).toBe(2);});
  it("enforces domain roles and reserves repair actions for the administrator",()=>{const editor={actorId:"editor",roles:["professional_editor"] as const};assertAuthorized(editor,"card:edit","coremail-professional");expect(()=>assertAuthorized(editor,"card:edit","presales-general")).toThrow("permission_denied");expect(()=>assertAuthorized(editor,"repair:publish")).toThrow("permission_denied");assertAuthorized({actorId:"admin",roles:["admin"]},"repair:publish");});
  it("separates answer-review ingestion from operator reading and triage",()=>{assertAuthorized({actorId:"bridge",roles:["service"]},"answer_review:ingest");expect(()=>assertAuthorized({actorId:"bridge",roles:["service"]},"answer_review:read")).toThrow("permission_denied");assertAuthorized({actorId:"operator",roles:["operator"]},"answer_review:read");assertAuthorized({actorId:"operator",roles:["operator"]},"answer_review:triage");expect(()=>assertAuthorized({actorId:"operator",roles:["operator"]},"answer_review:ingest")).toThrow("permission_denied");});
  it("uses hashed bearer tokens",()=>{const token="service-token-with-more-than-24-characters";const actor={actorId:"lunkr",roles:["service"] as const};const auth=new StaticTokenAuthorizer([{tokenHash:createHash("sha256").update(token).digest("hex"),actor}]);expect(auth.authenticate(token)).toEqual(actor);expect(auth.authenticate("wrong")).toBeUndefined();});
  it("exchanges a hashed admin password for an expiring and revocable session while preserving service tokens",async()=>{let now=Date.parse("2026-08-05T00:00:00.000Z");const password="correct-horse-123",passwordHash=await createAdminPasswordHash(password,Buffer.alloc(16,7)),serviceToken="service-token-with-more-than-24-characters",auth=new KnowledgeOpsAuthorizer([{tokenHash:createHash("sha256").update(serviceToken).digest("hex"),actor:{actorId:"lunkr",roles:["service"]}}],{username:"admin",passwordHash,sessionTtlMs:60_000},()=>now);expect(passwordHash).not.toContain(password);expect(await auth.login("admin","wrong-password")).toBeUndefined();expect(await auth.login("unknown",password)).toBeUndefined();const session=await auth.login("admin",password);expect(session).toMatchObject({actor:{actorId:"admin",roles:["admin"]},expiresAt:"2026-08-05T00:01:00.000Z"});expect(session?.sessionToken).toMatch(/^[A-Za-z0-9_-]{43}$/u);expect(auth.authenticate(session?.sessionToken)).toMatchObject({actorId:"admin",roles:["admin"]});expect(auth.authenticate(serviceToken)).toMatchObject({actorId:"lunkr",roles:["service"]});auth.logout(session?.sessionToken);expect(auth.authenticate(session?.sessionToken)).toBeUndefined();const expiring=await auth.login("admin",password);now+=60_001;expect(auth.authenticate(expiring?.sessionToken)).toBeUndefined();});
});
