import { randomBytes, randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { ContentCipher } from "./crypto.js";
import { KnowledgeOpsService } from "./service.js";
import { InMemoryKnowledgeOpsStore } from "./store.js";

describe("KnowledgeOpsService",()=>{
  it("stores only encrypted feedback content and returns metadata-first lists",async()=>{const store=new InMemoryKnowledgeOpsStore();const service=new KnowledgeOpsService(store,new ContentCipher(randomBytes(32)));const actor={actorId:"lunkr",roles:["service"] as const};const caseId=randomUUID(),requestId=randomUUID();await service.ingestFeedback(actor,{caseId,requestId,pseudonymousUserId:"a".repeat(64),questionId:1,classification:"incorrect",comment:"版本不对",question:"原问题",answer:"原答案",answerStatus:"answered",referenceCount:2,answeredAt:new Date().toISOString(),submittedAt:new Date().toISOString(),source:"lunkr_direct"});const raw=await store.getFeedback(caseId);expect(JSON.stringify(raw)).not.toContain("原问题");const list=await service.listFeedback({actorId:"operator",roles:["operator"]});expect(list[0]).not.toHaveProperty("encryptedPayload");const detail=await service.feedbackDetail({actorId:"operator",roles:["operator"]},caseId);expect(detail).toMatchObject({question:"原问题",answer:"原答案",comment:"版本不对"});});
  it("prevents a card author from approving their own revision",async()=>{const service=new KnowledgeOpsService(new InMemoryKnowledgeOpsStore(),new ContentCipher(randomBytes(32)));const content={cardSchemaVersion:1,title:"测试卡",canonicalQuestion:"这是一个测试问题吗？",questionFamily:"test_family",aliases:[],applicability:{products:[],versions:["*"],scenarios:[],excludeWhen:[]},obligations:[{id:"O1",label:"给出结论",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:[],forbiddenClaims:[],preferredEvidencePaths:[]}],answerTemplate:"测试答案",owner:"作者",reviewers:[],regressionCaseIds:[]};const revision=await service.createCardRevision({actorId:"author",roles:["professional_editor"]},"PRO-TEST-CARD","coremail-professional",content,"a".repeat(40));await expect(service.reviewRevision({actorId:"author",roles:["professional_reviewer"]},revision.revisionId,"approved","")).rejects.toThrow("creator_cannot_self_approve");const review=await service.reviewRevision({actorId:"reviewer",roles:["professional_reviewer"]},revision.revisionId,"approved","通过");expect(review.decision).toBe("approved");});
  it("claims queued jobs once under concurrency",async()=>{const store=new InMemoryKnowledgeOpsStore();await store.enqueueJob("compile_catalog",{});const claims=await Promise.all(Array.from({length:20},(_,index)=>store.claimJob(`worker-${index}`)));expect(claims.filter(Boolean)).toHaveLength(1);});
});
