import { randomBytes, randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import { ContentCipher } from "./crypto.js";
import { KnowledgeOpsService } from "./service.js";
import { InMemoryKnowledgeOpsStore } from "./store.js";

describe("KnowledgeOpsService",()=>{
  it("stores only encrypted feedback content and returns metadata-first lists",async()=>{const store=new InMemoryKnowledgeOpsStore();const service=new KnowledgeOpsService(store,new ContentCipher(randomBytes(32)));const actor={actorId:"lunkr",roles:["service"] as const};const caseId=randomUUID(),requestId=randomUUID();await service.ingestFeedback(actor,{caseId,requestId,pseudonymousUserId:"a".repeat(64),questionId:1,classification:"incorrect",comment:"版本不对",question:"原问题",answer:"原答案",answerStatus:"answered",referenceCount:2,answeredAt:new Date().toISOString(),submittedAt:new Date().toISOString(),source:"lunkr_direct"});const raw=await store.getFeedback(caseId);expect(JSON.stringify(raw)).not.toContain("原问题");const list=await service.listFeedback({actorId:"operator",roles:["operator"]});expect(list[0]).not.toHaveProperty("encryptedPayload");const detail=await service.feedbackDetail({actorId:"operator",roles:["operator"]},caseId);expect(detail).toMatchObject({question:"原问题",answer:"原答案",comment:"版本不对"});});
  it("encrypts a user-proposed answer and exposes it only in authorized detail",async()=>{const store=new InMemoryKnowledgeOpsStore();const service=new KnowledgeOpsService(store,new ContentCipher(randomBytes(32)));const actor={actorId:"lunkr",roles:["service"] as const};const caseId=randomUUID();await service.ingestFeedback(actor,{caseId,requestId:randomUUID(),pseudonymousUserId:"b".repeat(64),questionId:2,classification:"correction",comment:"",proposedAnswer:"用户认为的正确答案",question:"原问题",answer:"原答案",answerStatus:"answered",referenceCount:1,answeredAt:new Date().toISOString(),submittedAt:new Date().toISOString(),source:"lunkr_direct"});const raw=await store.getFeedback(caseId);expect(JSON.stringify(raw)).not.toContain("用户认为的正确答案");const list=await service.listFeedback({actorId:"operator",roles:["operator"]});expect(list[0]).not.toHaveProperty("proposedAnswer");const detail=await service.feedbackDetail({actorId:"operator",roles:["operator"]},caseId);expect(detail).toMatchObject({classification:"correction",proposedAnswer:"用户认为的正确答案"});});
  it("rejects correction feedback without a proposed answer",async()=>{const service=new KnowledgeOpsService(new InMemoryKnowledgeOpsStore(),new ContentCipher(randomBytes(32)));await expect(service.ingestFeedback({actorId:"lunkr",roles:["service"]},{caseId:randomUUID(),requestId:randomUUID(),pseudonymousUserId:"c".repeat(64),questionId:3,classification:"correction",comment:"",question:"原问题",answer:"原答案",answerStatus:"answered",referenceCount:0,answeredAt:new Date().toISOString(),submittedAt:new Date().toISOString(),source:"lunkr_direct"})).rejects.toThrow();});
  it("encrypts the Lunkr chat name and audits operator classification correction",async()=>{const store=new InMemoryKnowledgeOpsStore();const service=new KnowledgeOpsService(store,new ContentCipher(randomBytes(32)));const caseId=randomUUID();await service.ingestFeedback({actorId:"lunkr",roles:["service"]},{caseId,requestId:randomUUID(),pseudonymousUserId:"d".repeat(64),userDisplayName:"Wayne 黎政良",questionId:4,classification:"useful",comment:"",question:"原问题",answer:"原答案",answerStatus:"answered",referenceCount:1,answeredAt:new Date().toISOString(),submittedAt:new Date().toISOString(),source:"lunkr_direct"});const raw=await store.getFeedback(caseId);expect(JSON.stringify(raw)).not.toContain("Wayne 黎政良");const list=await service.listFeedback({actorId:"operator",roles:["operator"]});expect(list[0]).toMatchObject({userDisplayName:"Wayne 黎政良",classification:"useful"});await service.triageFeedback({actorId:"operator",roles:["operator"]},caseId,{classification:"missing",status:"in_review"});const detail=await service.feedbackDetail({actorId:"operator",roles:["operator"]},caseId);expect(detail).toMatchObject({userDisplayName:"Wayne 黎政良",classification:"missing",status:"in_review"});const audit=await store.listAudit();expect(audit.at(0)).toMatchObject({action:"feedback.triage",metadata:{previousClassification:"useful",classification:"missing",previousStatus:"new",status:"in_review"}});expect(JSON.stringify(audit)).not.toContain("Wayne 黎政良");});
  it("prevents a card author from approving their own revision",async()=>{const service=new KnowledgeOpsService(new InMemoryKnowledgeOpsStore(),new ContentCipher(randomBytes(32)));const content={cardSchemaVersion:1,title:"测试卡",canonicalQuestion:"这是一个测试问题吗？",questionFamily:"test_family",aliases:[],applicability:{products:[],versions:["*"],scenarios:[],excludeWhen:[]},obligations:[{id:"O1",label:"给出结论",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:[],forbiddenClaims:[],preferredEvidencePaths:[]}],answerTemplate:"测试答案",owner:"作者",reviewers:[],regressionCaseIds:[]};const revision=await service.createCardRevision({actorId:"author",roles:["professional_editor"]},"PRO-TEST-CARD","coremail-professional",content,"a".repeat(40));await expect(service.reviewRevision({actorId:"author",roles:["professional_reviewer"]},revision.revisionId,"approved","")).rejects.toThrow("creator_cannot_self_approve");const review=await service.reviewRevision({actorId:"reviewer",roles:["professional_reviewer"]},revision.revisionId,"approved","通过");expect(review.decision).toBe("approved");});
  it("claims queued jobs once under concurrency",async()=>{const store=new InMemoryKnowledgeOpsStore();await store.enqueueJob("compile_catalog",{});const claims=await Promise.all(Array.from({length:20},(_,index)=>store.claimJob(`worker-${index}`)));expect(claims.filter(Boolean)).toHaveLength(1);});
});
