import { randomUUID } from "node:crypto";
import { afterEach,expect,it,vi } from "vitest";
import { HttpFeedbackClient } from "./feedback-client.js";

afterEach(()=>vi.unstubAllGlobals());
it("submits explicit feedback with bearer authentication",async()=>{const fetchMock=vi.fn(async(_input:string|URL|Request,_init?:RequestInit)=>new Response(null,{status:201}));vi.stubGlobal("fetch",fetchMock);const client=new HttpFeedbackClient({baseUrl:"http://127.0.0.1:19830",serviceToken:"service-token-with-more-than-24-characters"});await client.submit({caseId:randomUUID(),requestId:randomUUID(),pseudonymousUserId:"a".repeat(64),questionId:1,classification:"useful",comment:"",question:"问题",answer:"答案",answerStatus:"answered",referenceCount:1,answeredAt:new Date().toISOString(),submittedAt:new Date().toISOString(),source:"lunkr_direct",audit:{event:"feedback_submitted",occurredAt:new Date().toISOString()}});expect(fetchMock).toHaveBeenCalledOnce();expect(fetchMock.mock.calls[0]?.[1]?.headers).toMatchObject({authorization:"Bearer service-token-with-more-than-24-characters"});});
it("submits an automatic review to the dedicated endpoint",async()=>{const urls:string[]=[];const fetchMock=vi.fn(async(input:string|URL|Request)=>{urls.push(String(input));return new Response(null,{status:201});});vi.stubGlobal("fetch",fetchMock);const client=new HttpFeedbackClient({baseUrl:"http://127.0.0.1:19830",serviceToken:"service-token-with-more-than-24-characters"});const now=new Date().toISOString();await client.submitReview({reviewId:randomUUID(),requestId:randomUUID(),pseudonymousUserId:"a".repeat(64),questionId:1,question:"问题",answer:"答案",answerStatus:"answered",scope:"professional",references:[],answeredAt:now,submittedAt:now,source:"lunkr_direct"});expect(urls).toEqual(["http://127.0.0.1:19830/v1/answer-reviews"]);});
it("loads, appends and ends persistent conversation context",async()=>{const urls:string[]=[],fetchMock=vi.fn(async(input:string|URL|Request)=>{urls.push(String(input));return new Response(urls.length===1?JSON.stringify({recentTurns:[]}):null,{status:urls.length===1?200:201,headers:{"content-type":"application/json"}});});vi.stubGlobal("fetch",fetchMock);const client=new HttpFeedbackClient({baseUrl:"http://127.0.0.1:19830",serviceToken:"service-token-with-more-than-24-characters"}),user="a".repeat(64),now=new Date().toISOString();await expect(client.loadConversation(user,6)).resolves.toEqual({recentTurns:[]});await client.appendConversation({turnId:randomUUID(),requestId:randomUUID(),pseudonymousUserId:user,questionId:1,rawQuestion:"问题",resolvedQuestion:"完整问题",contextUsed:false,inheritedSubjects:[],answerStatus:"answered",answeredAt:now,expiresAt:new Date(Date.parse(now)+86_400_000).toISOString(),source:"lunkr_direct"});await client.endConversation(user,"manual",now);expect(urls).toEqual(["http://127.0.0.1:19830/v1/conversations/context","http://127.0.0.1:19830/v1/conversations/turns","http://127.0.0.1:19830/v1/conversations/end"]);});
it("rejects plaintext remote feedback endpoints",()=>{expect(()=>new HttpFeedbackClient({baseUrl:"http://example.com",serviceToken:"service-token-with-more-than-24-characters"})).toThrow("feedback_service_url_must_be_https_or_loopback");});
