import { describe,expect,it } from "vitest";
import type { ModelClient } from "@pseagent/app/embedded";
import type { AnswerCard, AnswerReviewResult } from "@pseagent/knowledge-governance-contracts";
import { IndependentAnswerReviewer } from "./answer-reviewer.js";

const card:AnswerCard={cardSchemaVersion:1,cardId:"PRO-REVIEW-TEST",domain:"coremail-professional",title:"迁移前置",canonicalQuestion:"迁移前要做什么？",questionFamily:"migration_prerequisites",aliases:[],applicability:{products:[],versions:["*"],scenarios:[],excludeWhen:[]},obligations:[{id:"O1",label:"准备认证与协议",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:["客户端专用密码","IMAP","SMTP"],forbiddenClaims:["普通登录密码一定可以直接用于迁移"],preferredEvidencePaths:[]}],answerTemplate:"",owner:"运营",reviewers:[],reviewStatus:"approved",regressionCaseIds:[]};
const pass:AnswerReviewResult={verdict:"pass",score:95,summary:"完整",defects:[],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};
const evidence=[{index:1,title:"正式资料",path:"wiki/concepts/a.md",content:"迁移应生成客户端专用密码并开启 IMAP 和 SMTP。"}];
const projectCard:AnswerCard={...card,cardId:"PRO-PROJECT-DATA",title:"项目规模",canonicalQuestion:"华为项目规模如何？",questionFamily:"project_scale",obligations:[{id:"O1",label:"华为项目规模",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:["东莞节点","英国节点"],forbiddenClaims:["不得将华为项目用户数描述为产品容量上限"],preferredEvidencePaths:["wiki/entities/东莞节点.md","wiki/entities/英国节点.md"]}]};
const projectEvidence=[{index:1,title:"东莞节点",path:"wiki/entities/东莞节点.md",content:"# 东莞节点\n### 华为Coremail邮件系统项目\n东莞节点预测用户基数为10W。"},{index:2,title:"英国节点",path:"wiki/entities/英国节点.md",content:"# 英国节点\n### 华为Coremail邮件系统项目\n英国节点预测用户基数为2W。"}];

describe("IndependentAnswerReviewer",()=>{
  it("downgrades a model pass when governed concepts are absent",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"请勾选收取全部邮件。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result.verdict).toBe("needs_review");expect(result.score).toBeLessThanOrEqual(69);expect(result.defects.some((item)=>item.category==="coverage_gap"&&item.evidence.includes("客户端专用密码"))).toBe(true);});
  it("keeps a fully governed paraphrase as pass instead of requiring exact phrase copying",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"生成客户端的专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("does not require every sibling concept when the reviewed obligation is covered",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移时认证协议是什么？",answer:"迁移前需要开启 IMAP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("does not fail an otherwise covered answer merely because a legacy card uses an abstract concept label",async()=>{const abstractCard:AnswerCard={...card,obligations:[{...card.obligations[0]!,requiredConcepts:["deliveragent 核心功能"]}]};const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"DA 做什么？",answer:"deliveragent 负责病毒扫描、反垃圾检查并将邮件投递至 mssvr。",answerStatus:"answered",evidence:[{...evidence[0]!,content:"deliveragent 负责病毒扫描、反垃圾检查并将邮件投递至 mssvr。"}],evidenceIssues:[],governedCard:abstractCard,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("fails a forbidden governed claim even when the model says pass",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"普通登录密码一定可以直接用于迁移；同时开启客户端专用密码、IMAP、SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card});expect(result.verdict).toBe("fail");expect(result.score).toBeLessThanOrEqual(39);});
  it("normalizes an internally inconsistent low pass score to the pass range",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,score:10})).review({question:"迁移前要做什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:80});});
  it("allows project numbers directly supported by formal evidence",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]})).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户，英国节点预测2万用户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],governedCard:projectCard});expect(result.verdict).toBe("pass");});
  it("drops an unsupported-citation defect when the quoted numeric claim appears directly in formal evidence",async()=>{const claim="每用户邮箱容量 5G、实际占用率 40%、Search 索引按 MS 容量的 10%、UD 按每用户 10M、归档按 MS 容量的 150%，并增加 30% 空间预留。";const falsePositive:AnswerReviewResult={verdict:"fail",score:39,summary:"数字缺少证据",defects:[{category:"citation_gap",severity:"critical",summary:"没有正式证据直接支持该项目数字。",evidence:`- 另一套参数为${claim} [2]`}],obligationChecks:[]};const result=await new IndependentAnswerReviewer(scripted(falsePositive)).review({question:"容量怎样估算？",answer:claim,answerStatus:"answered",evidence:[{index:2,title:"存储估算",path:"wiki/concepts/capacity.md",content:`资源清单采用经验参数。参数包括${claim}`}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("recognizes a directly supported numeric claim split across a formal evidence list",async()=>{const claim="邮箱实际存储占用率 60%、Search 索引存储率 30%、每用户邮件索引 10M、归档数据为邮箱存储量的 120%、归档索引为归档数据的 30%。";const falsePositive:AnswerReviewResult={verdict:"fail",score:39,summary:"数字缺少证据",defects:[{category:"citation_gap",severity:"critical",summary:"没有正式证据直接支持该项目数字。",evidence:`- 例如，一套方案使用${claim} [1]`}],obligationChecks:[]};const result=await new IndependentAnswerReviewer(scripted(falsePositive)).review({question:"容量怎样估算？",answer:claim,answerStatus:"answered",evidence:[{index:1,title:"存储估算",path:"wiki/concepts/capacity.md",content:"方案使用以下参数：\n- 邮箱实际存储占用率：60%；\n- Search 索引存储率：30%；\n- 每用户邮件索引：10M；\n- 归档数据：邮箱存储量的 120%；\n- 归档索引：归档数据的 30%。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("keeps a genuine support defect even when its evidence excerpt has a runtime citation number",async()=>{const unsupported:AnswerReviewResult={verdict:"fail",score:39,summary:"数字缺少证据",defects:[{category:"citation_gap",severity:"critical",summary:"没有正式证据直接支持该项目数字。",evidence:"项目固定需要 999T 存储 [1]"}],obligationChecks:[]};const result=await new IndependentAnswerReviewer(scripted(unsupported)).review({question:"容量怎样估算？",answer:"项目固定需要 999T 存储。",answerStatus:"answered",evidence:[{index:1,title:"存储估算",path:"wiki/concepts/capacity.md",content:"正式资料只说明必须根据现网数据测算。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"fail"});expect(result.defects).toContainEqual(expect.objectContaining({category:"citation_gap",severity:"critical"}));});
  it("allows an explicit safe boundary around supported project data even when the model parrots the forbidden rule",async()=>{const falsePositive:AnswerReviewResult={verdict:"fail",score:39,summary:"回答已正确说明案例边界",defects:[{category:"logic_gap",severity:"critical",summary:"项目案例数据不得扩大为所有客户的通用配置、产品上限或新项目承诺。",evidence:"兴业银行项目记录为 6 万用户；这是项目案例，不代表产品通用容量上限，也不能直接承诺给新客户。"}],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};const result=await new IndependentAnswerReviewer(scripted(falsePositive)).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户；这是项目案例，不代表产品通用容量上限，也不能直接承诺给新客户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],governedCard:projectCard});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("does not require runtime citation numbers in an answer template",async()=>{const citationOnly:AnswerReviewResult={verdict:"needs_review",score:60,summary:"缺少编号",defects:[{category:"citation_gap",severity:"major",summary:"答案未标注引用编号 [1]",evidence:"需要手工引用序号"}],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};const result=await new IndependentAnswerReviewer(scripted(citationOnly)).review({question:"迁移前要做什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("allows a formally supported safe not-covered boundary to pass",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"是否支持尚无正式资料的新协议？",answer:"现有正式资料没有该协议的支持结论，不能据此确认支持。",answerStatus:"not_covered",evidence:[{index:1,title:"协议边界",path:"wiki/concepts/protocol.md",content:"当前资料仅记录 SMTP、POP3 与 IMAP。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("does not auto-pass when a governed family candidate exists but matching was unavailable",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"自然语言卡族问法",answer:"有依据但可能漏掉治理卡义务。",answerStatus:"answered",evidence:[{index:1,title:"正式资料",path:"wiki/concepts/a.md",content:"正式内容。"}],evidenceIssues:[],answerCardMatch:{matchType:"none",confidence:"none",reason:"family_match_unavailable",candidateCount:1}});expect(result.verdict).toBe("needs_review");expect(result.defects).toContainEqual(expect.objectContaining({category:"planning_gap",severity:"major"}));});
  it("describes a family activation failure as a governance warning with guard details",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前还要准备什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardMatch:{matchType:"family",confidence:"high"},answerCardActivation:{activated:false,reason:"guard_rejected",issueCodes:["customer_input_request_unmapped"]}});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"planning_gap",severity:"major",summary:expect.stringContaining("高置信匹配已批准答案卡问题族"),evidence:expect.stringContaining("customer_input_request_unmapped")}));expect(result.defects.some((defect)=>defect.summary.includes("精确命中"))).toBe(false);});
  it("rejects supported case data when it is expanded into a product promise",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]})).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户，英国节点预测2万用户，因此所有客户的产品容量上限承诺为10万用户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],governedCard:projectCard});expect(result.verdict).toBe("fail");expect(result.defects.some((item)=>item.category==="logic_gap")).toBe(true);});
});

function scripted(result:AnswerReviewResult):ModelClient{return{completeJson:async<T>()=>result as T,completeText:async()=>""};}
