import { createHash,randomBytes,randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdtemp,readFile,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach,describe,expect,it } from "vitest";
import type { ModelClient } from "@pseagent/app/embedded";
import type { AnswerReviewResult } from "@pseagent/knowledge-governance-contracts";
import { ContentCipher,InMemoryKnowledgeOpsStore,KnowledgeOpsService } from "@pseagent/knowledge-ops";
import { IndependentAnswerReviewer } from "./answer-reviewer.js";
import { SafeGitWorkspace } from "./git-workspace.js";
import { SnapshotManager } from "./snapshot-manager.js";
import { KnowledgeOpsWorker } from "./worker.js";

const temporary:string[]=[];afterEach(async()=>{await Promise.all(temporary.splice(0).map((root)=>rm(root,{recursive:true,force:true})));});

describe("answer-review worker",()=>{
  it("independently flags the real Tencent migration answer when governed prerequisites are missing",async()=>{const workspace=path.resolve(import.meta.dirname,"../../../.."),professional=path.join(workspace,"coremail-professional"),general=path.join(workspace,"presales-general"),relative="wiki/concepts/腾讯企业邮箱迁移前置设置.md",bytes=await readFile(path.join(professional,...relative.split("/"))),revision=execFileSync("git",["-C",professional,"rev-parse","HEAD"],{encoding:"utf8"}).trim();const store=new InMemoryKnowledgeOpsStore(),cipher=new ContentCipher(randomBytes(32)),service=new KnowledgeOpsService(store,cipher),now=new Date().toISOString(),reviewId=randomUUID();await service.ingestAnswerReview({actorId:"bridge",roles:["service"]},{reviewId,requestId:randomUUID(),pseudonymousUserId:"a".repeat(64),userDisplayName:"Wayne 黎政良",questionId:1,question:"腾讯企业邮箱迁移到Coremail前需要哪些设置？",answer:"确认收取我的文件夹，并选择收取全部邮件。不同版本界面可能不同，通讯录和日程需另行核实。",answerStatus:"answered",scope:"professional",references:[{index:1,project:"coremail-professional",title:"腾讯企业邮箱迁移前置设置",path:relative,revision,contentHash:createHash("sha256").update(bytes).digest("hex")}],answeredAt:now,submittedAt:now,source:"lunkr_direct",answerCardActivation:{activated:false,reason:"shadow",obligationCount:0}});const root=await mkdtemp(path.join(tmpdir(),"pse-review-worker-"));temporary.push(root);const modelResult:AnswerReviewResult={verdict:"pass",score:95,summary:"模型初判通过",defects:[],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"},{obligationId:"O2",covered:true,explanation:"已覆盖"}]};const worker=new KnowledgeOpsWorker("review-worker",{store,sources:[{domain:"coremail-professional",root:professional},{domain:"presales-general",root:general}],snapshots:new SnapshotManager(path.join(root,"snapshots")),git:new SafeGitWorkspace([professional,general],path.join(root,"worktrees")),cipher,answerReviewer:new IndependentAnswerReviewer(scripted(modelResult))});expect(await worker.runOnce()).toBe(true);expect(await store.getAnswerReview(reviewId)).toMatchObject({processingStatus:"completed",verdict:"needs_review",workflowStatus:"open"});const detail=await service.answerReviewDetail({actorId:"operator",roles:["operator"]},reviewId);expect(detail?.result?.defects.some((defect)=>defect.evidence.includes("客户端专用密码"))).toBe(true);expect((await store.listJobs())[0]).toMatchObject({type:"answer_review",status:"completed"});},30_000);

  it("leaves an open errored record when the independent model is unavailable",async()=>{const workspace=path.resolve(import.meta.dirname,"../../../.."),professional=path.join(workspace,"coremail-professional"),general=path.join(workspace,"presales-general"),store=new InMemoryKnowledgeOpsStore(),cipher=new ContentCipher(randomBytes(32)),service=new KnowledgeOpsService(store,cipher),now=new Date().toISOString(),reviewId=randomUUID();await service.ingestAnswerReview({actorId:"bridge",roles:["service"]},{reviewId,requestId:randomUUID(),pseudonymousUserId:"b".repeat(64),questionId:2,question:"测试问题",answer:"测试回答",answerStatus:"answered",scope:"general",references:[],answeredAt:now,submittedAt:now,source:"lunkr_direct"});const root=await mkdtemp(path.join(tmpdir(),"pse-review-worker-error-"));temporary.push(root);const unavailable:ModelClient={completeJson:async()=>{throw new Error("model_unavailable");},completeText:async()=>{throw new Error("model_unavailable");}};const worker=new KnowledgeOpsWorker("review-worker",{store,sources:[{domain:"coremail-professional",root:professional},{domain:"presales-general",root:general}],snapshots:new SnapshotManager(path.join(root,"snapshots")),git:new SafeGitWorkspace([professional,general],path.join(root,"worktrees")),cipher,answerReviewer:new IndependentAnswerReviewer(unavailable)});expect(await worker.runOnce()).toBe(true);expect(await store.getAnswerReview(reviewId)).toMatchObject({processingStatus:"errored",verdict:"pending",workflowStatus:"open",errorCode:"model_unavailable"});expect((await store.listJobs())[0]).toMatchObject({status:"failed",errorCode:"model_unavailable"});},30_000);
});

function scripted(result:AnswerReviewResult):ModelClient{return{completeJson:async<T>()=>result as T,completeText:async()=>""};}
