import { describe,expect,it } from "vitest";
import type { ModelClient } from "@pseagent/app/embedded";
import type { AnswerCard, AnswerReviewResult } from "@pseagent/knowledge-governance-contracts";
import { IndependentAnswerReviewer } from "./answer-reviewer.js";

const card:AnswerCard={cardSchemaVersion:1,cardId:"PRO-REVIEW-TEST",domain:"coremail-professional",title:"迁移前置",canonicalQuestion:"迁移前要做什么？",questionFamily:"migration_prerequisites",aliases:[],applicability:{products:[],versions:["*"],scenarios:[],excludeWhen:[]},obligations:[{id:"O1",label:"准备认证与协议",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:["客户端专用密码","IMAP","SMTP"],forbiddenClaims:["普通登录密码一定可以直接用于迁移"],preferredEvidencePaths:[]}],answerTemplate:"",owner:"运营",reviewers:[],reviewStatus:"approved",regressionCaseIds:[]};
const pass:AnswerReviewResult={verdict:"pass",score:95,summary:"完整",defects:[],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};
const evidence=[{index:1,title:"正式资料",path:"wiki/concepts/a.md",content:"迁移应生成客户端专用密码并开启 IMAP 和 SMTP。"}];
const projectCard:AnswerCard={...card,cardId:"PRO-PROJECT-DATA",title:"项目规模",canonicalQuestion:"华为项目规模如何？",questionFamily:"project_scale",obligations:[{id:"O1",label:"华为项目规模",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:["东莞节点","英国节点"],forbiddenClaims:["不得将华为项目用户数描述为产品容量上限"],preferredEvidencePaths:["wiki/entities/东莞节点.md","wiki/entities/英国节点.md"]}]};
const projectEvidence=[{index:1,title:"东莞节点",path:"wiki/entities/东莞节点.md",content:"# 东莞节点\n### 华为Coremail邮件系统项目\n东莞节点预测用户基数为10W。"},{index:2,title:"英国节点",path:"wiki/entities/英国节点.md",content:"# 英国节点\n### 华为Coremail邮件系统项目\n英国节点预测用户基数为2W。"}];

describe("IndependentAnswerReviewer",()=>{
  it("instructs the independent model to audit every explicitly enumerated item",async()=>{let system="";const model:ModelClient={completeJson:async<T>(input:Parameters<ModelClient["completeJson"]>[0])=>{system=input.messages[0]?.content??"";return{...pass,obligationChecks:[]} as T;},completeText:async()=>""};await new IndependentAnswerReviewer(model).review({question:"分别说明经济、用户、技术和 Coach 四类角色",answer:"经济、用户、技术和 Coach 均按行为识别。",answerStatus:"answered",evidence:[{index:1,title:"角色",path:"wiki/concepts/roles.md",content:"四类角色按行为识别。"}],evidenceIssues:[]});expect(system).toContain("必须逐项检查 answer 是否给出各项的定义、判断标准或当前问题要求的结论");expect(system).toContain("只提到名称、只给孤立例子或只完整回答其中一项，不能判为完整覆盖");expect(system).toContain("主体步骤完整但遗漏相关证据边界时不能判为 pass");});
  it("downgrades a model pass when one coordinated framework component is omitted",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"怎样先建立相关性再按角色下钻？",answer:"用 Do the Last Thing First 建立相关性，再以 Inverted Pyramid 按需深入。",answerStatus:"answered",evidence:[{index:1,title:"结果优先结构",path:"wiki/concepts/results-first.md",content:"该结构包括 **Do the Last Thing First**（先展示最终结果）、**Illustration**（简洁画面）和 **Inverted Pyramid**（倒金字塔结构）三个相互配合的方法。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"coverage_gap",severity:"major",evidence:expect.stringContaining("Illustration")}));});
  it("downgrades a model pass when strict framework boundaries are omitted",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"怎样面向多角色下钻证据？",answer:"先展示最终结果，用 Illustration 简洁画面情境化，再以 Inverted Pyramid 按需深入。",answerStatus:"answered",evidence:[{index:1,title:"结果优先结构",path:"wiki/concepts/results-first.md",content:"该结构包括 **Do the Last Thing First**（先展示最终结果）、**Illustration**（简洁画面）和 **Inverted Pyramid**（倒金字塔结构）三个相互配合的方法。\n### 边界与风险\n- 敏感内容需使用脱敏或示意环境\n- 不能用虚构客户数据暗示已实现的承诺"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"coverage_gap",severity:"major",summary:expect.stringContaining("强边界"),evidence:expect.stringContaining("脱敏")}));});
  it("downgrades a model pass for a collection truncated after item one",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"实施前还要确认什么？",answer:"实施前需确认以下事项：1）确认用户所属组织。",answerStatus:"answered",evidence:[{index:1,title:"实施确认",path:"wiki/concepts/implementation.md",content:"实施前需要确认用户所属组织、产品版本和实际组织配置。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"coverage_gap",severity:"major",summary:expect.stringContaining("只出现第 1 项")}));});
  it("downgrades a model pass when a declared five-step answer only contains step one",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"黄灯怎样核验？",answer:"具体五步结构为：1. 暂停推进。",answerStatus:"answered",evidence:[{index:1,title:"黄灯对话",path:"wiki/concepts/traffic-light.md",content:"五步结构为暂停、陈述信号、说明影响、提出问题和接受结果。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"coverage_gap",severity:"major",summary:expect.stringContaining("集合数量")}));});
  it("downgrades a model pass for a check list truncated after item one",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"网络要检查什么？",answer:"网络层面需要检查：1) nginx 节点具备 DNS 能力。",answerStatus:"answered",evidence:[{index:1,title:"网络检查",path:"wiki/concepts/network.md",content:"需要检查 DNS、TCP 25 和 TCP 6610。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"coverage_gap",severity:"major"}));});
  it("keeps a complete rendered check list as pass",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"网络要检查什么？",answer:"网络层面需要检查：1) DNS；2) TCP 25；3) TCP 6610。",answerStatus:"answered",evidence:[{index:1,title:"网络检查",path:"wiki/concepts/network.md",content:"需要检查 DNS、TCP 25 和 TCP 6610。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("downgrades a model pass when a collection skips a middle ordinal",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"实施前还要确认什么？",answer:"实施前需确认以下事项：一是确认组织；二是确认等级；四是确认配置。",answerStatus:"answered",evidence:[{index:1,title:"实施确认",path:"wiki/concepts/implementation.md",content:"实施前需要确认组织、等级、版本和实际配置。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"coverage_gap",severity:"major",summary:expect.stringContaining("编号不连续")}));});
  it("downgrades a model pass when governed concepts are absent",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"请勾选收取全部邮件。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result.verdict).toBe("needs_review");expect(result.score).toBeLessThanOrEqual(69);expect(result.defects.some((item)=>item.category==="coverage_gap"&&item.evidence.includes("客户端专用密码"))).toBe(true);});
  it("keeps a fully governed paraphrase as pass instead of requiring exact phrase copying",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"生成客户端的专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("does not require every sibling concept when the reviewed obligation is covered",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移时认证协议是什么？",answer:"迁移前需要开启 IMAP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("does not fail an otherwise covered answer merely because a legacy card uses an abstract concept label",async()=>{const abstractCard:AnswerCard={...card,obligations:[{...card.obligations[0]!,requiredConcepts:["deliveragent 核心功能"]}]};const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"DA 做什么？",answer:"deliveragent 负责病毒扫描、反垃圾检查并将邮件投递至 mssvr。",answerStatus:"answered",evidence:[{...evidence[0]!,content:"deliveragent 负责病毒扫描、反垃圾检查并将邮件投递至 mssvr。"}],evidenceIssues:[],governedCard:abstractCard,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("fails a forbidden governed claim even when the model says pass",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"普通登录密码一定可以直接用于迁移；同时开启客户端专用密码、IMAP、SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card});expect(result.verdict).toBe("fail");expect(result.score).toBeLessThanOrEqual(39);});
  it("normalizes an internally inconsistent low pass score to the pass range",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,score:10})).review({question:"迁移前要做什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:80});});
  it("allows project numbers directly supported by formal evidence",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]})).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户，英国节点预测2万用户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],governedCard:projectCard});expect(result.verdict).toBe("pass");});
  it("drops an unsupported-citation defect when the quoted numeric claim appears directly in formal evidence",async()=>{const claim="每用户邮箱容量 5G、实际占用率 40%、Search 索引按 MS 容量的 10%、UD 按每用户 10M、归档按 MS 容量的 150%，并增加 30% 空间预留。";const falsePositive:AnswerReviewResult={verdict:"fail",score:39,summary:"数字缺少证据",defects:[{category:"citation_gap",severity:"critical",summary:"没有正式证据直接支持该项目数字。",evidence:`- 另一套参数为${claim} [2]`}],obligationChecks:[]};const result=await new IndependentAnswerReviewer(scripted(falsePositive)).review({question:"容量怎样估算？",answer:claim,answerStatus:"answered",evidence:[{index:2,title:"存储估算",path:"wiki/concepts/capacity.md",content:`资源清单采用经验参数。参数包括${claim}`}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("recognizes a directly supported numeric claim split across a formal evidence list",async()=>{const claim="邮箱实际存储占用率 60%、Search 索引存储率 30%、每用户邮件索引 10M、归档数据为邮箱存储量的 120%、归档索引为归档数据的 30%。";const falsePositive:AnswerReviewResult={verdict:"fail",score:39,summary:"数字缺少证据",defects:[{category:"citation_gap",severity:"critical",summary:"没有正式证据直接支持该项目数字。",evidence:`- 例如，一套方案使用${claim} [1]`}],obligationChecks:[]};const result=await new IndependentAnswerReviewer(scripted(falsePositive)).review({question:"容量怎样估算？",answer:claim,answerStatus:"answered",evidence:[{index:1,title:"存储估算",path:"wiki/concepts/capacity.md",content:"方案使用以下参数：\n- 邮箱实际存储占用率：60%；\n- Search 索引存储率：30%；\n- 每用户邮件索引：10M；\n- 归档数据：邮箱存储量的 120%；\n- 归档索引：归档数据的 30%。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("keeps a genuine support defect even when its evidence excerpt has a runtime citation number",async()=>{const unsupported:AnswerReviewResult={verdict:"fail",score:39,summary:"数字缺少证据",defects:[{category:"citation_gap",severity:"critical",summary:"没有正式证据直接支持该项目数字。",evidence:"项目固定需要 999T 存储 [1]"}],obligationChecks:[]};const result=await new IndependentAnswerReviewer(scripted(unsupported)).review({question:"容量怎样估算？",answer:"项目固定需要 999T 存储。",answerStatus:"answered",evidence:[{index:1,title:"存储估算",path:"wiki/concepts/capacity.md",content:"正式资料只说明必须根据现网数据测算。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"fail"});expect(result.defects).toContainEqual(expect.objectContaining({category:"citation_gap",severity:"critical"}));});
  it("allows an explicit safe boundary around supported project data even when the model parrots the forbidden rule",async()=>{const falsePositive:AnswerReviewResult={verdict:"fail",score:39,summary:"回答已正确说明案例边界",defects:[{category:"logic_gap",severity:"critical",summary:"项目案例数据不得扩大为所有客户的通用配置、产品上限或新项目承诺。",evidence:"兴业银行项目记录为 6 万用户；这是项目案例，不代表产品通用容量上限，也不能直接承诺给新客户。"}],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};const result=await new IndependentAnswerReviewer(scripted(falsePositive)).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户；这是项目案例，不代表产品通用容量上限，也不能直接承诺给新客户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],governedCard:projectCard});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("does not require runtime citation numbers in an answer template",async()=>{const citationOnly:AnswerReviewResult={verdict:"needs_review",score:60,summary:"缺少编号",defects:[{category:"citation_gap",severity:"major",summary:"答案未标注引用编号 [1]",evidence:"需要手工引用序号"}],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};const result=await new IndependentAnswerReviewer(scripted(citationOnly)).review({question:"迁移前要做什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("allows a formally supported safe not-covered boundary to pass",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"是否支持尚无正式资料的新协议？",answer:"现有正式资料没有该协议的支持结论，不能据此确认支持。",answerStatus:"not_covered",evidence:[{index:1,title:"协议边界",path:"wiki/concepts/protocol.md",content:"当前资料仅记录 SMTP、POP3 与 IMAP。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("allows a safe partially answered boundary instead of failing only on delivery status",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"能否确认最新版本已修复全部漏洞并写进合同？",answer:"现有资料支持合同需审批，但无法确认最新版本已修复全部漏洞，也不能直接作为合同承诺。",answerStatus:"partially_answered",evidence:[{index:1,title:"合同审批",path:"wiki/concepts/contract.md",content:"合同内容必须经过正式审批。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("drops a reviewer claim that an explicit safe boundary was not stated",async()=>{const falsePositive:AnswerReviewResult={verdict:"needs_review",score:69,summary:"结论不清晰",defects:[{category:"coverage_gap",severity:"major",summary:"回答未明确给出不能确认的结论",evidence:"仅以无法确认代替直接回答，导致结论不清晰"}],obligationChecks:[]};const result=await new IndependentAnswerReviewer(scripted(falsePositive)).review({question:"能否确认全部漏洞均已修复？",answer:"现有正式资料无法确认全部漏洞均已修复。",answerStatus:"not_covered",evidence:[{index:1,title:"安全边界",path:"wiki/concepts/security.md",content:"结论仅适用于报告范围。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("does not treat one explicitly labeled coverage gap as a truncated collection",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"哪些内容尚未确认？",answer:"尚未确认的部分：\n对象：目标版本；缺失信息：当前支持结论。",answerStatus:"partially_answered",evidence:[{index:1,title:"边界",path:"wiki/concepts/boundary.md",content:"当前资料未覆盖目标版本。"}],evidenceIssues:[]});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("does not auto-pass when a governed family candidate exists but matching was unavailable",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[]})).review({question:"自然语言卡族问法",answer:"有依据但可能漏掉治理卡义务。",answerStatus:"answered",evidence:[{index:1,title:"正式资料",path:"wiki/concepts/a.md",content:"正式内容。"}],evidenceIssues:[],answerCardMatch:{matchType:"none",confidence:"none",reason:"family_match_unavailable",candidateCount:1}});expect(result.verdict).toBe("needs_review");expect(result.defects).toContainEqual(expect.objectContaining({category:"planning_gap",severity:"major"}));});
  it("describes a family activation failure as a governance warning with guard details",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前还要准备什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],governedCard:card,answerCardMatch:{matchType:"family",confidence:"high"},answerCardActivation:{activated:false,reason:"guard_rejected",issueCodes:["customer_input_request_unmapped"]}});expect(result).toMatchObject({verdict:"needs_review",score:69});expect(result.defects).toContainEqual(expect.objectContaining({category:"planning_gap",severity:"major",summary:expect.stringContaining("高置信匹配已批准答案卡问题族"),evidence:expect.stringContaining("customer_input_request_unmapped")}));expect(result.defects.some((defect)=>defect.summary.includes("精确命中"))).toBe(false);});
  it("does not audit obligations from a family card that never activated",async()=>{const inactiveDefect:AnswerReviewResult={verdict:"needs_review",score:60,summary:"错误审计未激活卡片",defects:[{category:"coverage_gap",severity:"major",summary:"必答项 O1 未完整覆盖",evidence:"未覆盖无关卡片内容"}],obligationChecks:[{obligationId:"O1",covered:false,explanation:"未覆盖"}]};const result=await new IndependentAnswerReviewer(scripted(inactiveDefect)).review({question:"怎样用红黄绿灯标记命题？",answer:"绿灯表示有行为证据，黄灯要减速核验，红灯应接受并记录。",answerStatus:"answered",evidence:[{index:1,title:"交通灯",path:"wiki/concepts/traffic-light.md",content:"绿灯有行为证据；黄灯减速核验；红灯接受并记录。"}],evidenceIssues:[],governedCard:card,answerCardMatch:{matchType:"family",confidence:"high"},answerCardActivation:{activated:false,reason:"binding_unmapped"}});expect(result.defects.some((defect)=>defect.summary.includes("必答项 O1"))).toBe(false);expect(result.defects).toContainEqual(expect.objectContaining({category:"planning_gap",summary:expect.stringContaining("高置信匹配")}));});
  it("rejects supported case data when it is expanded into a product promise",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]})).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户，英国节点预测2万用户，因此所有客户的产品容量上限承诺为10万用户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],governedCard:projectCard});expect(result.verdict).toBe("fail");expect(result.defects.some((item)=>item.category==="logic_gap")).toBe(true);});
});

function scripted(result:AnswerReviewResult):ModelClient{return{completeJson:async<T>()=>result as T,completeText:async()=>""};}
