import { describe,expect,it } from "vitest";
import type { ModelClient } from "@pseagent/app/embedded";
import type { AnswerCard, AnswerReviewResult } from "@pseagent/knowledge-governance-contracts";
import { IndependentAnswerReviewer } from "./answer-reviewer.js";

const card:AnswerCard={cardSchemaVersion:1,cardId:"PRO-REVIEW-TEST",domain:"coremail-professional",title:"迁移前置",canonicalQuestion:"迁移前要做什么？",questionFamily:"migration_prerequisites",aliases:[],applicability:{products:[],versions:["*"],scenarios:[],excludeWhen:[]},obligations:[{id:"O1",label:"准备认证与协议",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:["客户端专用密码","IMAP","SMTP"],forbiddenClaims:["普通登录密码一定可以直接用于迁移"],preferredEvidencePaths:[]}],answerTemplate:"",owner:"运营",reviewers:[],reviewStatus:"approved",regressionCaseIds:[]};
const pass:AnswerReviewResult={verdict:"pass",score:95,summary:"完整",defects:[],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};
const evidence=[{index:1,title:"正式资料",path:"wiki/concepts/a.md",content:"迁移应生成客户端专用密码并开启 IMAP 和 SMTP。"}];
const projectCard:AnswerCard={...card,cardId:"PRO-PROJECT-DATA",title:"项目规模",canonicalQuestion:"华为项目规模如何？",questionFamily:"project_scale",obligations:[{id:"O1",label:"华为项目规模",required:true,domains:["coremail-professional"],evidencePolicy:"direct",requiredConcepts:["东莞节点","英国节点"],forbiddenClaims:["不得将华为项目用户数描述为产品容量上限"],preferredEvidencePaths:["wiki/entities/东莞节点.md","wiki/entities/英国节点.md"]}]};
const projectEvidence=[{index:1,title:"东莞节点",path:"wiki/entities/东莞节点.md",content:"# 东莞节点\n### 华为Coremail邮件系统项目\n东莞节点预测用户基数为10W。"},{index:2,title:"英国节点",path:"wiki/entities/英国节点.md",content:"# 英国节点\n### 华为Coremail邮件系统项目\n英国节点预测用户基数为2W。"}];

describe("IndependentAnswerReviewer",()=>{
  it("downgrades a model pass when governed concepts are absent",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"请勾选收取全部邮件。",answerStatus:"answered",evidence,evidenceIssues:[],exactCard:card,answerCardActivation:{activated:true}});expect(result.verdict).toBe("needs_review");expect(result.score).toBeLessThanOrEqual(69);expect(result.defects.some((item)=>item.category==="coverage_gap"&&item.evidence.includes("客户端专用密码"))).toBe(true);});
  it("keeps a fully governed paraphrase as pass instead of requiring exact phrase copying",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"生成客户端的专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],exactCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:95,defects:[]});});
  it("fails a forbidden governed claim even when the model says pass",async()=>{const result=await new IndependentAnswerReviewer(scripted(pass)).review({question:"迁移前要做什么？",answer:"普通登录密码一定可以直接用于迁移；同时开启客户端专用密码、IMAP、SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],exactCard:card});expect(result.verdict).toBe("fail");expect(result.score).toBeLessThanOrEqual(39);});
  it("normalizes an internally inconsistent low pass score to the pass range",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,score:10})).review({question:"迁移前要做什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],exactCard:card,answerCardActivation:{activated:true}});expect(result).toMatchObject({verdict:"pass",score:80});});
  it("allows project numbers directly supported by formal evidence",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]})).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户，英国节点预测2万用户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],exactCard:projectCard});expect(result.verdict).toBe("pass");});
  it("does not require runtime citation numbers in an answer template",async()=>{const citationOnly:AnswerReviewResult={verdict:"needs_review",score:60,summary:"缺少编号",defects:[{category:"citation_gap",severity:"major",summary:"答案未标注引用编号 [1]",evidence:"需要手工引用序号"}],obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]};const result=await new IndependentAnswerReviewer(scripted(citationOnly)).review({question:"迁移前要做什么？",answer:"生成客户端专用密码，并开启 IMAP 与 SMTP。",answerStatus:"answered",evidence,evidenceIssues:[],exactCard:card});expect(result).toMatchObject({verdict:"pass",defects:[]});});
  it("rejects supported case data when it is expanded into a product promise",async()=>{const result=await new IndependentAnswerReviewer(scripted({...pass,obligationChecks:[{obligationId:"O1",covered:true,explanation:"已覆盖"}]})).review({question:"华为项目规模如何？",answer:"**华为项目**\n东莞节点预测10万用户，英国节点预测2万用户，因此所有客户的产品容量上限承诺为10万用户。",answerStatus:"answered",evidence:projectEvidence,evidenceIssues:[],exactCard:projectCard});expect(result.verdict).toBe("fail");expect(result.defects.some((item)=>item.category==="logic_gap")).toBe(true);});
});

function scripted(result:AnswerReviewResult):ModelClient{return{completeJson:async<T>()=>result as T,completeText:async()=>""};}
