import { execFileSync } from "node:child_process";
import { mkdtemp,mkdir,rm,writeFile } from "node:fs/promises";
import os from "node:os";import path from "node:path";
import { afterEach,expect,it } from "vitest";
import { SafeGitWorkspace } from "./git-workspace.js";
const temporary:string[]=[];afterEach(async()=>{for(const item of temporary.splice(0))await rm(item,{recursive:true,force:true});});
it("writes only allowlisted knowledge paths in a detached worktree",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"pse-git-fixture-"));temporary.push(root);await mkdir(path.join(root,"wiki","queries"),{recursive:true});await writeFile(path.join(root,"wiki","queries","old.md"),"old\n");git(root,"init");git(root,"config","user.email","test@example.invalid");git(root,"config","user.name","Test");git(root,"add",".");git(root,"commit","-m","初始提交");const base=git(root,"rev-parse","HEAD").trim();const worktrees=path.join(root,"worktrees");const safe=new SafeGitWorkspace([root],worktrees);const result=await safe.writeRevision(root,base,[{relativePath:"wiki/queries/new.md",content:"new\n"}],"新增答案卡");expect(result.diff).toContain("new.md");expect(git(root,"cat-file","-t",result.revision).trim()).toBe("commit");await expect(safe.writeRevision(root,base,[{relativePath:"../escape.md",content:"bad"}],"非法")).rejects.toThrow("knowledge_path_not_allowlisted");},15_000);
it("fast-forwards a clean knowledge repository and creates an auditable revert commit",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"pse-git-publish-")),worktrees=await mkdtemp(path.join(os.tmpdir(),"pse-git-worktrees-"));temporary.push(root,worktrees);await mkdir(path.join(root,"wiki","queries"),{recursive:true});await writeFile(path.join(root,"wiki","queries","answer.md"),"old\n");git(root,"init");git(root,"config","user.email","test@example.invalid");git(root,"config","user.name","Test");git(root,"add",".");git(root,"commit","-m","初始提交");const base=git(root,"rev-parse","HEAD").trim(),safe=new SafeGitWorkspace([root],worktrees),published=await safe.publishRevision(root,base,[{relativePath:"wiki/queries/answer.md",content:"new\n"}],"发布修订");expect(git(root,"rev-parse","HEAD").trim()).toBe(published.revision);expect(git(root,"show","HEAD:wiki/queries/answer.md")).toBe("new\n");const reverted=await safe.revertPublishedRevision(root,published.revision,published.revision,"回滚修订");expect(reverted.revision).not.toBe(published.revision);expect(git(root,"show","HEAD:wiki/queries/answer.md")).toBe("old\n");await writeFile(path.join(root,"wiki","queries","answer.md"),"dirty\n");await expect(safe.assertCleanRevision(root,reverted.revision)).rejects.toThrow("knowledge_repository_dirty");},15_000);
it("pushes only a clean fast-forward revision to the configured upstream",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"pse-git-upstream-")),remote=await mkdtemp(path.join(os.tmpdir(),"pse-git-remote-")),worktrees=await mkdtemp(path.join(os.tmpdir(),"pse-git-worktrees-"));temporary.push(root,remote,worktrees);git(remote,"init","--bare");await mkdir(path.join(root,"wiki","queries"),{recursive:true});await writeFile(path.join(root,"wiki","queries","answer.md"),"old\n");git(root,"init");git(root,"config","user.email","test@example.invalid");git(root,"config","user.name","Test");git(root,"add",".");git(root,"commit","-m","初始提交");git(root,"branch","-M","main");git(root,"remote","add","origin",remote);git(root,"push","-u","origin","main");const base=git(root,"rev-parse","HEAD").trim(),safe=new SafeGitWorkspace([root],worktrees),published=await safe.publishRevision(root,base,[{relativePath:"wiki/queries/answer.md",content:"new\n"}],"批次修订"),pushed=await safe.pushCurrent(root,published.revision);expect(pushed).toMatchObject({remoteName:"origin",remoteBranch:"main",revision:published.revision,aheadCount:1});expect(git(remote,"rev-parse","refs/heads/main").trim()).toBe(published.revision);},20_000);
it.runIf(process.platform==="win32")("checks out a large repository path without Windows filename truncation",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"pse-git-longpath-")),worktrees=await mkdtemp(path.join(os.tmpdir(),"pse-git-longpath-worktrees-"));temporary.push(root,worktrees);const nested=path.join(root,"raw",...Array.from({length:9},(_,index)=>`正式资料目录-${String(index).padStart(2,"0")}-abcdefghijklmnop`),"evidence.md");await mkdir(path.dirname(nested),{recursive:true});await writeFile(nested,"formal evidence\n");await mkdir(path.join(root,"wiki","queries"),{recursive:true});await writeFile(path.join(root,"wiki","queries","old.md"),"old\n");git(root,"init");git(root,"config","user.email","test@example.invalid");git(root,"config","user.name","Test");execFileSync("git",["-c","core.longpaths=true","-C",root,"add","."],{windowsHide:true});git(root,"commit","-m","初始提交");const base=git(root,"rev-parse","HEAD").trim(),safe=new SafeGitWorkspace([root],worktrees),result=await safe.writeRevision(root,base,[{relativePath:"wiki/queries/new.md",content:"new\n"}],"新增答案卡");expect(git(root,"cat-file","-t",result.revision).trim()).toBe("commit");},60_000);
function git(root:string,...args:string[]){return execFileSync("git",["-C",root,...args],{encoding:"utf8",windowsHide:true});}
