export type ViewName="dashboard"|"issues"|"repair"|"batches"|"feedback"|"cards"|"regressions"|"releases"|"audit";
export type FeedbackClassification="useful"|"incorrect"|"missing"|"review_requested"|"evidence"|"correction";
export type FeedbackStatus="new"|"triaged"|"in_review"|"resolved"|"rejected";
export type ReviewProcessingStatus="queued"|"running"|"completed"|"errored";
export type ReviewVerdict="pending"|"pass"|"needs_review"|"fail";
export type ReviewWorkflowStatus="open"|"in_review"|"resolved"|"dismissed";
export interface Dashboard {issues:{actionable:number;urgent:number;overdue:number;validating:number;readyToPublish:number;byPriority:Record<IssuePriority,number>};repairBatches:{queued:number;publishing:number;published:number;failed:number};feedback:Record<string,number>;answerReviews:{pendingHuman:number;passed:number;errored:number;total:number};cardsByStatus:Record<string,number>;jobs:Record<string,number>;activeReleaseId?:string;}
export interface FeedbackMeta {caseId:string;requestId:string;pseudonymousUserId:string;userDisplayName?:string;classification:FeedbackClassification;status:FeedbackStatus;answerStatus:string;scope?:string;referenceCount:number;source:string;createdAt:string;updatedAt:string;}
export interface FeedbackDetail extends FeedbackMeta {question:string;answer:string;comment:string;proposedAnswer?:string;questionId:number;answeredAt:string;answerCardMatch?:Record<string,unknown>;}
export interface AnswerReviewMeta {reviewId:string;requestId:string;pseudonymousUserId:string;userDisplayName?:string;questionPreview:string;processingStatus:ReviewProcessingStatus;verdict:ReviewVerdict;workflowStatus:ReviewWorkflowStatus;answerStatus:string;scope?:string;referenceCount:number;source:string;model:string;score?:number;defectCount:number;errorCode?:string;createdAt:string;updatedAt:string;}
export interface AnswerReviewDetail extends AnswerReviewMeta {questionId:number;question:string;answer:string;references:Array<Record<string,unknown>>;answeredAt:string;answerCardMatch?:Record<string,unknown>;answerCardActivation?:Record<string,unknown>;result?:{summary:string;defects:Array<{category:string;severity:string;summary:string;evidence:string}>;obligationChecks:Array<{obligationId:string;covered:boolean;explanation:string}>};}
export type IssuePriority="p0"|"p1"|"p2"|"p3";
export type IssueStatus="open"|"in_progress"|"validating"|"resolved"|"dismissed";
export type IssueCategory="knowledge_gap"|"retrieval_gap"|"planning_gap"|"coverage_gap"|"logic_gap"|"citation_gap"|"expression_gap"|"user_incorrect"|"user_missing"|"review_requested"|"evidence"|"correction"|"judgement_conflict"|"review_error";
export interface IssueSummary {issueId:string;fingerprint:string;title:string;priority:IssuePriority;status:IssueStatus;category:IssueCategory;scope?:string;answerCardKey?:string;slaDueAt:string;firstSeenAt:string;lastSeenAt:string;createdAt:string;updatedAt:string;occurrenceCount:number;affectedUserCount:number;}
export interface IssueOccurrence {occurrenceId:string;issueId:string;sourceType:"answer_review"|"feedback";sourceId:string;requestId:string;pseudonymousUserId:string;createdAt:string;}
export interface IssueDetail extends IssueSummary {occurrences:IssueOccurrence[];}
export interface IssuePage {items:IssueSummary[];total:number;}
export type RepairTargetKind="answer_card"|"knowledge_page"|"retrieval_rule"|"system_fix";
export type RepairDraftStatus="generating"|"draft_ready"|"validating"|"validation_failed"|"ready_to_publish"|"publishing"|"published"|"failed";
export type RepairRegressionKind="canonical"|"alias"|"colloquial"|"follow_up"|"negative";
export interface RepairObligation {id:string;label:string;evidencePolicy:"direct"|"synthesis"|"customer_input";requiredConcepts:string[];forbiddenClaims:string[];preferredEvidencePaths:string[];}
export interface RepairProposal {rootCause:IssueCategory;targetKind:RepairTargetKind;targetDomain?:string;targetPath?:string;cardId?:string;title:string;canonicalQuestion:string;aliases:string[];answerTemplate:string;obligations:RepairObligation[];regressionQuestions:Array<{kind:RepairRegressionKind;question:string}>;generationSummary:string;publishable:boolean;blockingReason?:string;}
export interface RepairEvidenceSummary {loadedCount:number;revalidatedReferenceCount:number;issues:string[];}
export interface RepairDraft {draftId:string;issueId:string;status:RepairDraftStatus;targetKind?:RepairTargetKind;targetDomain?:string;targetPath?:string;baseGitRevision?:string;model:"deepseek_v4_flash";createdBy:string;errorCode?:string;createdAt:string;updatedAt:string;proposal?:RepairProposal;evidenceSummary?:RepairEvidenceSummary;}
export interface RepairValidation {validationId:string;draftId:string;issueId:string;status:"queued"|"running"|"passed"|"failed";totalCases:number;passedCases:number;model:"deepseek_v4_flash";errorCode?:string;createdAt:string;completedAt?:string;result?:{passed?:boolean;targeted?:Array<{kind:RepairRegressionKind;question:string;passed:boolean;exactMatch:boolean;assessment?:{passed:boolean;explanation:string}|null;review?:{verdict:string;summary:string}|null}>;fullRegression?:Array<{caseId:string;passed:boolean}>;evidenceIssues?:string[];};}
export type RepairRemoteSyncStatus="pending"|"pushing"|"synced"|"failed"|"compensated";
export interface RepairPublication {publicationId:string;batchId?:string;draftId:string;issueId:string;status:"pending"|"publishing"|"published"|"failed"|"rolled_back";targetDomain:string;targetPath:string;baseGitRevision:string;remoteSyncStatus:RepairRemoteSyncStatus;remoteName?:string;remoteBranch?:string;resultingGitRevision?:string;catalogHash?:string;snapshotReleaseId?:string;previousReleaseId?:string;createdBy:string;errorCode?:string;createdAt:string;publishedAt?:string;rolledBackAt?:string;}
export interface RepairBatch {batchId:string;status:"queued"|"publishing"|"published"|"failed"|"rolled_back";itemCount:number;domains:string[];catalogHash?:string;snapshotReleaseId?:string;previousReleaseId?:string;createdBy:string;errorCode?:string;createdAt:string;publishedAt?:string;rolledBackAt?:string;}
export interface RepairBatchDetail extends RepairBatch {publications:RepairPublication[];}
export interface CardRevision {revisionId:string;cardId:string;domain:string;revision:number;status:string;content:Record<string,unknown>;createdBy:string;baseGitRevision:string;createdAt:string;updatedAt:string;}
export interface OpsJob {jobId:string;type:string;status:string;attempts:number;lockedBy?:string;errorCode?:string;createdAt:string;updatedAt:string;}
export interface RegressionRun {runId:string;status:string;totalCases:number;passedCases:number;report?:{model?:string;passed?:boolean;summary?:{averageScore?:number;p95LatencyMs?:number;safetyFailures?:number};suites?:unknown[];kinds?:unknown[]};createdAt:string;completedAt?:string;}
export interface Release {releaseId:string;professionalRevision:string;generalRevision:string;cardCatalogHash:string;status:string;createdBy:string;approvedBy:string[];createdAt:string;activatedAt?:string;}
export interface Audit {auditId:string;actorId:string;action:string;resourceType:string;resourceId:string;metadata:Record<string,unknown>;createdAt:string;}
