export type ViewName="dashboard"|"issues"|"evidence"|"repair"|"batches"|"feedback"|"cards"|"regressions"|"releases"|"audit";
export type FeedbackClassification="useful"|"incorrect"|"missing"|"review_requested"|"evidence"|"correction";
export type FeedbackStatus="new"|"triaged"|"in_review"|"resolved"|"rejected";
export interface ListPage<T> {items:T[];total:number;}
export type ReviewProcessingStatus="queued"|"running"|"completed"|"errored";
export type ReviewVerdict="pending"|"pass"|"needs_review"|"fail";
export type ReviewWorkflowStatus="open"|"in_review"|"resolved"|"dismissed";
export interface ConversationTurn {turnId:string;sessionId:string;turnIndex:number;requestId:string;questionId:number;parentTurnId?:string;parentRequestId?:string;rawQuestion:string;resolvedQuestion:string;contextUsed:boolean;inheritedSubjects:string[];answerOutline?:string;answerStatus:string;scope?:string;answerCardMatch?:Record<string,unknown>;answeredAt:string;createdAt:string;}
export interface ConversationRelation {session:{sessionId:string;pseudonymousUserId:string;source:"lunkr_direct";startedAt:string;lastActiveAt:string;expiresAt:string;endedAt?:string;endReason?:string};current:ConversationTurn;parent?:ConversationTurn;chain:ConversationTurn[];}
export interface Dashboard {issues:{actionable:number;awaitingEvidence:number;urgent:number;overdue:number;validating:number;readyToPublish:number;byPriority:Record<IssuePriority,number>};repairBatches:{queued:number;publishing:number;published:number;failed:number};feedback:Record<string,number>;answerReviews:{pendingHuman:number;passed:number;errored:number;total:number};cardsByStatus:Record<string,number>;jobs:Record<string,number>;activeReleaseId?:string;}
export interface FeedbackMeta {caseId:string;requestId:string;pseudonymousUserId:string;userDisplayName?:string;classification:FeedbackClassification;status:FeedbackStatus;answerStatus:string;scope?:string;referenceCount:number;source:string;linkedReviewId?:string;linkedReviewVerdict?:ReviewVerdict;createdAt:string;updatedAt:string;}
export interface FeedbackDetail extends FeedbackMeta {question:string;answer:string;comment:string;proposedAnswer?:string;questionId:number;answeredAt:string;answerCardMatch?:Record<string,unknown>;conversation?:ConversationRelation;}
export interface AnswerReviewMeta {reviewId:string;requestId:string;pseudonymousUserId:string;userDisplayName?:string;questionPreview:string;rawQuestionPreview?:string;contextUsed?:boolean;processingStatus:ReviewProcessingStatus;verdict:ReviewVerdict;workflowStatus:ReviewWorkflowStatus;answerStatus:string;scope?:string;referenceCount:number;source:string;model:string;score?:number;defectCount:number;errorCode?:string;createdAt:string;updatedAt:string;}
export interface AnswerReviewDetail extends AnswerReviewMeta {questionId:number;question:string;answer:string;references:Array<Record<string,unknown>>;answeredAt:string;answerCardMatch?:Record<string,unknown>;answerCardActivation?:Record<string,unknown>;result?:{summary:string;defects:Array<{category:string;severity:string;summary:string;evidence:string}>;obligationChecks:Array<{obligationId:string;covered:boolean;explanation:string}>};conversation?:ConversationRelation;}
export type IssuePriority="p0"|"p1"|"p2"|"p3";
export type IssueStatus="open"|"in_progress"|"awaiting_evidence"|"validating"|"resolved"|"dismissed";
export type IssueCategory="knowledge_gap"|"retrieval_gap"|"planning_gap"|"coverage_gap"|"logic_gap"|"citation_gap"|"expression_gap"|"user_incorrect"|"user_missing"|"review_requested"|"evidence"|"correction"|"judgement_conflict"|"review_error";
export interface IssueSummary {issueId:string;fingerprint:string;title:string;priority:IssuePriority;status:IssueStatus;category:IssueCategory;scope?:string;answerCardKey?:string;slaDueAt:string;firstSeenAt:string;lastSeenAt:string;createdAt:string;updatedAt:string;occurrenceCount:number;affectedUserCount:number;}
export interface IssueOccurrence {occurrenceId:string;issueId:string;sourceType:"answer_review"|"feedback";sourceId:string;requestId:string;pseudonymousUserId:string;createdAt:string;}
export interface IssueDetail extends IssueSummary {occurrences:IssueOccurrence[];}
export interface IssuePage {items:IssueSummary[];total:number;}
export interface RepairEvidenceRequest {summary:string;requiredMaterials:string[];acceptanceCriteria:string[];}
export interface EvidenceNeed {issue:IssueSummary;draftId:string;targetDomain?:string;topic:string;blockingReason:string;evidenceRequest:RepairEvidenceRequest;updatedAt:string;}
export interface EvidenceNeedPage {items:EvidenceNeed[];total:number;}
export type RepairTargetKind="answer_card"|"knowledge_page"|"retrieval_rule"|"system_fix";
export type RepairDraftStatus="generating"|"draft_ready"|"validating"|"validation_failed"|"ready_to_publish"|"publishing"|"published"|"failed";
export type RepairRegressionKind="canonical"|"alias"|"colloquial"|"follow_up"|"negative";
export interface RepairObligation {id:string;label:string;evidencePolicy:"direct"|"synthesis"|"customer_input";requiredConcepts:string[];forbiddenClaims:string[];preferredEvidencePaths:string[];}
export interface RepairProposal {rootCause:IssueCategory;targetKind:RepairTargetKind;targetDomain?:string;targetPath?:string;cardId?:string;title:string;canonicalQuestion:string;aliases:string[];answerTemplate:string;obligations:RepairObligation[];regressionQuestions:Array<{kind:RepairRegressionKind;question:string}>;generationSummary:string;publishable:boolean;blockingReason?:string;blockingKind?:"evidence_required"|"system_fix_required"|"human_decision_required"|"candidate_invalid";evidenceRequest?:RepairEvidenceRequest;}
export interface RepairEvidenceSummary {loadedCount:number;revalidatedReferenceCount:number;issues:string[];}
export interface RepairDraft {draftId:string;issueId:string;status:RepairDraftStatus;targetKind?:RepairTargetKind;targetDomain?:string;targetPath?:string;baseGitRevision?:string;model:"deepseek_v4_flash";createdBy:string;errorCode?:string;createdAt:string;updatedAt:string;proposal?:RepairProposal;evidenceSummary?:RepairEvidenceSummary;}
export type RepairValidationStage="card_match"|"obligation_coverage"|"forbidden_claim"|"evidence_support"|"independent_review"|"rule_conflict";
export type RepairSuggestedAction="modify_answer"|"modify_rule"|"add_evidence"|"human_review";
export interface RepairValidationDiagnostic {stage:RepairValidationStage;obligationId?:string;field?:"requiredConcepts"|"forbiddenClaims"|"answerTemplate"|"preferredEvidencePaths";triggerText:string;rule:string;message:string;suggestedAction:RepairSuggestedAction;evidencePaths:string[];}
export interface RepairRuleConflict {code:"required_forbidden_conflict"|"answer_forbidden_conflict"|"evidence_supported_project_data_forbidden"|"numeric_boundary_conflict";obligationId:string;field:"requiredConcepts"|"forbiddenClaims"|"answerTemplate";triggerText:string;rule:string;message:string;suggestedAction:RepairSuggestedAction;evidencePaths:string[];}
export interface RepairValidation {validationId:string;draftId:string;issueId:string;status:"queued"|"running"|"passed"|"failed";totalCases:number;passedCases:number;model:"deepseek_v4_flash";errorCode?:string;createdAt:string;completedAt?:string;result?:{passed?:boolean;outcome?:"passed"|"validation_failed"|"rule_conflict";validationFingerprint?:string;reused?:boolean;reusedFromValidationId?:string;ruleConflicts?:RepairRuleConflict[];diagnostics?:RepairValidationDiagnostic[];targeted?:Array<{kind:RepairRegressionKind;question:string;passed:boolean;exactMatch:boolean;assessment?:{passed:boolean;explanation:string}|null;review?:{verdict:string;summary:string}|null;diagnostics?:RepairValidationDiagnostic[]}>;fullRegression?:Array<{caseId:string;passed:boolean}>;evidenceIssues?:string[];};}
export type RepairRemoteSyncStatus="pending"|"pushing"|"synced"|"failed"|"compensated";
export interface RepairPublication {publicationId:string;batchId?:string;draftId:string;issueId:string;status:"pending"|"publishing"|"published"|"failed"|"rolled_back";targetDomain:string;targetPath:string;baseGitRevision:string;remoteSyncStatus:RepairRemoteSyncStatus;remoteName?:string;remoteBranch?:string;resultingGitRevision?:string;catalogHash?:string;snapshotReleaseId?:string;previousReleaseId?:string;createdBy:string;errorCode?:string;createdAt:string;publishedAt?:string;rolledBackAt?:string;}
export type KnowledgeDeploymentStage="queued"|"running_global_regression"|"writing_git"|"pushing_github"|"reloading_engine"|"activating_snapshot"|"verifying_online"|"active"|"compensating"|"failed"|"rolled_back";
export interface RepairBatch {batchId:string;status:"queued"|"publishing"|"published"|"failed"|"rolled_back";deploymentStage:KnowledgeDeploymentStage;servingPreviousVersion:boolean;itemCount:number;domains:string[];targetProfessionalRevision?:string;targetGeneralRevision?:string;qualityRunId?:string;catalogHash?:string;snapshotReleaseId?:string;previousReleaseId?:string;createdBy:string;errorCode?:string;createdAt:string;publishedAt?:string;rolledBackAt?:string;}
export interface RepairBatchDetail extends RepairBatch {publications:RepairPublication[];}
export interface KnowledgeRuntimeStatus {state:"aligned"|"switching"|"degraded"|"unavailable";checkedAt:string;servingPreviousVersion:boolean;engineStatus:"ready"|"reloading"|"failed"|"unavailable";activeReleaseId?:string;targetReleaseId?:string;activeProfessionalRevision?:string;activeGeneralRevision?:string;engineProfessionalRevision?:string;engineGeneralRevision?:string;errorCode?:string;activeBatch?:RepairBatch;}
export interface CardRevision {revisionId:string;cardId:string;domain:string;revision:number;status:string;content:Record<string,unknown>;createdBy:string;baseGitRevision:string;createdAt:string;updatedAt:string;}
export interface CardRevisionPage {items:CardRevision[];total:number;}
export interface OpsJob {jobId:string;type:string;payload:Record<string,unknown>;status:string;attempts:number;availableAt:string;lockedBy?:string;result?:Record<string,unknown>;errorCode?:string;createdAt:string;updatedAt:string;}
export type ReleaseQualityQuestionKind="canonical"|"alias"|"colloquial"|"follow_up"|"negative";
export interface RegressionPlanCase {caseId:string;kind:ReleaseQualityQuestionKind;turn:number;question:string;}
export interface RegressionPlanSuite {suiteId:string;title:string;cases:RegressionPlanCase[];}
export interface RegressionPlan {model:"deepseek_v4_flash";suiteCount:4;caseCount:20;suites:RegressionPlanSuite[];}
export type RegressionProgressCaseStatus="queued"|"running"|"completed"|"passed"|"failed"|"error";
export interface RegressionProgressCase extends RegressionPlanCase {suiteId:string;suiteTitle:string;status:RegressionProgressCaseStatus;latencyMs?:number;answerStatus?:string;failure?:string;}
export interface RegressionProgress {kind:"release_quality_progress";model:"deepseek_v4_flash";totalCases:number;completedCases:number;passedCases:number;failedCases:number;currentCaseIds:string[];cases:RegressionProgressCase[];}
export interface RegressionRun {runId:string;status:string;totalCases:number;passedCases:number;report?:{model?:string;passed?:boolean;summary?:{total?:number;completed?:number;passedCases?:number;averageScore?:number;p95LatencyMs?:number;safetyFailures?:number;availabilityFailures?:number};suites?:Array<{suiteId:string;passed:boolean;passedCases:number;averageScore:number}>;kinds?:Array<{kind:string;passed:boolean;passedCases:number;averageScore:number}>;consistencyChecks?:Array<Record<string,unknown>>;cases?:Array<{caseId?:string;suiteId?:string;kind?:string;passed?:boolean;score?:number;checks?:Array<{category?:string;id?:string;passed?:boolean;detail?:string}>}>};createdAt:string;completedAt?:string;}
export interface Release {releaseId:string;professionalRevision:string;generalRevision:string;cardCatalogHash:string;status:string;createdBy:string;approvedBy:string[];createdAt:string;activatedAt?:string;}
export interface Audit {auditId:string;actorId:string;action:string;resourceType:string;resourceId:string;metadata:Record<string,unknown>;createdAt:string;}
